class orangehrm_xpaths:
    username_input_box = "//input[@name='username']"
    password_input_box = "//input[@name='password']"
    login_submit = "//button[@type='submit']"
    logout_dropdown = "//p[@class='oxd-userdropdown-name']"
    logout_button = "//a[text()='Logout']"
    invalid_cred = "/html/body/div/div[1]/div/div[1]/div/div[2]/div[2]/div/div[1]/div[1]"
    PIM_tab = "//ul[@class='oxd-main-menu']/li[2]/a"
    Add_empl_button = "(//button[@type='button']/i)[4]"
    First_name = "//input[@name='firstName']"
    Middle_name = "//input[@name='middleName']"
    Last_name = "//input[@name='lastName']"
    Empl_ID = "(//input[@class='oxd-input oxd-input--active'])[2]"
    save_buuton = "//button[@type='submit']"
    edit_existing_emp = "(//button[@class='oxd-icon-button oxd-table-cell-action-space'])[2]"
    contact_detail = "//a[text()='Contact Details']"
    st1 = "//div[@class='oxd-form-row']/div/div/div/div[2]/input[1]"
    st2 = "(//div[@class='oxd-form-row']/div/div/div/div[2]/input)[2]"
    city = "(//div[@class='oxd-form-row']/div/div/div/div[2]/input)[3]"
    state = "(//div[@class='oxd-form-row']/div/div/div/div[2]/input)[4]"
    zip_code = "(//div[@class='oxd-form-row']/div/div/div/div[2]/input)[5]"
    mobile_no = "(//div[@class='oxd-form-row']/div/div/div/div[2]/input)[7]"
    email = "(//input[@class='oxd-input oxd-input--active'])[10]"
    delete = "(//i[@class='oxd-icon bi-trash'])[1]"
    del_sbutton = "//div[@class='orangehrm-modal-footer']/button[2]"
    forgot_password = "//div[@class='orangehrm-login-forgot']/p"
    reset_username_input = "//input[normalize-space(@class)='oxd-input oxd-input--active']"
    reset_password_button = "//button[contains(normalize-space(@class),'orangehrm-forgot-password-button--reset')]"
    reset_password_successful = "//h6[contains(normalize-space(@class),'orangehrm-forgot-password-title')]"